name: game_stats
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^8.1.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  flutter_riverpod: ^2.5.1
  fl_chart: ^0.69.0
  intl: ^0.20.2
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  geolocator: ^13.0.2
  path: ^1.9.0
  collection: ^1.18.0
  url_launcher: ^6.3.0
  geocoding: ^3.0.0
  archive: ^3.6.1
  share_plus: ^10.0.2
  file_picker: ^8.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  generate: true

